openapi: 3.0.3
info:
  title: DCAT-AP-NO validator service
  description: The service validates a graph against dcat-ap-no specification
  version: '1.0'
  contact:
    name: Digitaliseringsdirektoratet
    url: 'https://digdir.no'
  license:
    name: License of API
    url: 'http://data.norge.no/nlod/no/2.0'
servers:
  - url: https://validator.staging.fellesdatakatalog.digdir
paths:
  /validator:
    post:
      description: Validates RDF graph and generates a validation report
      requestBody:
        description: A Multipart/form-data body containing one or more of the following parts
        content:
          multipart/form-data:
            schema:
              type: object
              properties: # Request parts
                  version:
                    type: string
                    description: an identifier of the version to be validated against
                  text:
                    type: string
                    description: a text string with RDF as turtle
                  url:
                    type: string
                    format: uri
                    description: a url pointing to a resource on the internet
                  file:
                    type: string
                    format: binary
                    description: a file containing RDF
            encoding:
              file:
                contentType: text/turtle
      responses:
        200:
          description: OK
          content:
            multipart/mixed:
              schema:
                type: object
                properties:
                  data:
                    type: string
                    description: a text string with the data sent for validaton
                  data_graph:
                    type: string
                    description: a turtle representantion of the data graph that got validated, including addtional triples
                  results_text:
                    type: string
                    description: a text representantion of the validaton report
                  results_graph:
                    type: string
                    description: a turtle representation of the validation report
              encoding:
                data:
                  contentType: text/turtle
                result_graph:
                  contentType: text/turtle
  /shapes:
    get:
      description: returns a list of shape graphs the validator can execute
      responses:
        200:
          description: OK
          content:
            text/turtle:
              schema:
                type: string
  /shapes/{id}:
    get:
      description: returns the content of a shape graph given by id
      parameters:
      - name: id
        in: path
        description: shape id
        required: true
        schema:
          type: string
      responses:
        200:
          description: OK
          content:
            text/turtle:
              schema:
                type: string
